// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEFssz3llpK_HvY__IJf2tED8bQt2iZnE',
    appId: '1:1001522263076:web:2d14f8fde76ad0f31094b1',
    messagingSenderId: '1001522263076',
    projectId: 'bau-recycle-8cf42',
    authDomain: 'bau-recycle-8cf42.firebaseapp.com',
    storageBucket: 'bau-recycle-8cf42.firebasestorage.app',
    measurementId: 'G-RVMZNKHN0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcnAgWxhE2u_yi00Ps4lOkELBHlfaHptU',
    appId: '1:1001522263076:android:2318f9b706ac02db1094b1',
    messagingSenderId: '1001522263076',
    projectId: 'bau-recycle-8cf42',
    storageBucket: 'bau-recycle-8cf42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvbtfotbSYPfVGL_7pJPpUdvAWEoidQ8I',
    appId: '1:1001522263076:ios:b74deec94792f2c21094b1',
    messagingSenderId: '1001522263076',
    projectId: 'bau-recycle-8cf42',
    storageBucket: 'bau-recycle-8cf42.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvbtfotbSYPfVGL_7pJPpUdvAWEoidQ8I',
    appId: '1:1001522263076:ios:b74deec94792f2c21094b1',
    messagingSenderId: '1001522263076',
    projectId: 'bau-recycle-8cf42',
    storageBucket: 'bau-recycle-8cf42.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEFssz3llpK_HvY__IJf2tED8bQt2iZnE',
    appId: '1:1001522263076:web:f21bb2553dd2290e1094b1',
    messagingSenderId: '1001522263076',
    projectId: 'bau-recycle-8cf42',
    authDomain: 'bau-recycle-8cf42.firebaseapp.com',
    storageBucket: 'bau-recycle-8cf42.firebasestorage.app',
    measurementId: 'G-C4VRVESMBN',
  );
}
